#!/bin/bash

stuff_file='public_html/stuff.html'
swell_file='public_html/swell-animations-status.html'

cd ~/Pathfinding/

# update project website files if needed
cp -u "$stuff_file" ~/public_html/
cp -u "$swell_file" ~/public_html/

if [ "x$1" != "x--force" ]; then
    git fetch &> /dev/null
    check=$(git log HEAD..origin/master --oneline | wc -l)

    sed -i "s/Last\spulled\sgit.*/Last pulled git $(date)<\/font><\/br>/" ~/public_html/swell-animations-status.html
    if [ "$check" -lt "1" ]; then
        exit;
    fi
fi

git pull --rebase &> /dev/null

for i in $(find . -name tex); do
    pushd "$i" &> /dev/null
    make pdf &> /dev/null
    popd &> /dev/null
done

for i in $(find . -name *.pdf); do
    mv "$i" ~/public_html/ &> /dev/null
done

sed -i "s/Last\supdated\sdocs.*/Last updated docs $(date)<\/font><br>/" ~/public_html/swell-animations-status.html
sed -i "s/Updated\ on\ .*/Updated on $(hostname)<\/font><br>/" ~/public_html/swell-animations-status.html
